<?php
//? INCLUDE_ONCE 
//? REQUIRE_ONCE

//? LA EXPRESION INCLUDE_ONCE FUNCIONA EXACTAMENTE COMO EL INCLUDE, NO ENTANTO SI EL SCRIPT YA FUE ANTERIORMENTE AGREGADO, PHP NO VUELVE A AGREGARLO

include_once 'config.php';
echo "\nAAA \n";
include_once 'config.php'; #ESTA LINEA NO SERA CARGADA NUEVAMENTE
echo "BBB \n";

//? EN EL CASO DE REQUIRE_ONCE FUNCIONA EXACTAMENTE COMO REQUIRE, CON EL MISMO COMPORTAMIENTO DE INCLUDE_ONCE, SI EL FICHERO YA FUE CARGADO NO LO CARGARA NUEVAMENTE

require_once 'config.php';
echo "\nCCC\n";
require_once 'config.php';
echo "DDD\n";
