<?php
//^ CSONSTANTE.
//^ LAS CONSTANTE SON VARIABLES CUYO VALOR NO ES ATRIBUIDO EN LA DIFINICION NO PUEDEN SER MODIFICADAS A LO LARGO DEL SCRIPT PHP

//^ PHP PERMITE DEFINIR CONSTANTE DE DOS FORMA: CON EL TERMINO CONST Y COMO METODO DEFINE.

//& CONST

//^ CONST ES USADO PARA DEFINIR CONSTANTES EN EL CONTEXTO DE LAS CLASES AL CONTRARIO DE LAS PROPIEDADES PUBLIC, PROTECTED O PRIVATE, LAS PROPIEDADES CONST ESTAN SIEMPRE VISIBLES(SON PUBLICAS). COMO NO PUEDEN SER MODIFICADAS EL VALOR, NO EXISTE RIESGO DE QUE QUEDEN EXPUESTAS.

//^ PARA DEFINIR UNA CONSTANTE, EL NOMBRE DEBE SER SIEMPRE EN MAYUSCULA, PUEDE SER USANDO _ NO ES NECESARIO EL SIGNO DE DOLAR COMO CON LAS VARIABLES NORMALES.

//! EJEMPLO A:
// class Circulo
// {
//   const PI = 3.14; //* Todas las constantes tienen que tener el valor atribuido siempre que son definidas.

// }

//* ES POSIBLE MOSTRAR SIN ESTANCIAR, PARECIDO A LOS STATIC
// echo Circulo::PI;

// echo "\n";

//* O CON INSTANCIA
// $c = new Circulo();
// echo $c::PI; //* NO ES VALIDO CON CONST $c->PI

//! FIN EJEMPLO A

//!EJEMPLO B:
//^ EL TERMINO CONST NO DEBE SER APLICADO A VARIABLES LOCALES O A PARAMETROS.
//^ DESDE PHP 5.3, EL TERMINO CONST PUEDE SER USANDO PARA CREAR CONSTANTES GLOBALES.
//^ ESAS CONSTANTES SON DEFINIDAS EN EL SCOPE GLOBAL DEL SCRIPT Y QUEDAN AUTOMATICAMENTE ACCESSIBLES.

// const APP_NAME = 'Mi aplicacion';
// echo APP_NAME . "\n";

// DENTRO DE UNA FUNCION
// function test()
// {
//   echo APP_NAME;
// }

// test();

// NO ES POSIBLE CONCATENAR CONST DE LA MISMA FORMA QUE HACEMOS CON VARIABLES
// echo "\nNombre: {APP_NAME}";
// DE ESTAR FORMA SI ES POSIBLE
// echo "\nNombre: " . APP_NAME;
//! FIN EJEMPLO B

//!EJEMPLO C:
//^ LA FUNCION DEFINE PERMITE DEFINIR CONSTANTES GLOBALES Y LOCALES, PERO NO PERMITE SER USADA DENTRO DEL CONTEXTO DE UNA CLASE.

// define('APP_NAME', 'Mi aplicacion');
// define('VERSION', '1.0.0');
// define('MOSTRAR_ERRORES', true);
// define('PI', 3.14);

// echo APP_NAME . "\n";

// SIEMPRE SE DEBE USAR LA CONSTANTE EN MAYUSCULA, ANTES SE PERMITIA EL TERCER PARAMETRO PARA PONERLA CASE INSENSITIVE

// define('CONSTANTE', 100, true); //YA NO SE USA.

//!FIN EJEMPLO C

//! EJEMPLO D
//^PARA VERIFICAR SI UNA CONSTANTE EXISTE
if (!defined('APP_NAME')) {
  define('APP_NAME', 'Mi aplicacion');
}

echo APP_NAME . "\n";

// O MAS COMUN AUN
defined('CONSTANTE') or define('CONSTANTE', 'valor');


// CON PHP 5.6 PODEMOS DEFINIR CONSTANTES CON UN ARRAY
const NOMBRES1 = ['Isaac', 'Abraham', 'Jose', 'Juan', 'Jesus'];
echo NOMBRES1[0] . "\n";

// CON PHP7, PODEMOS USAR ARRAY EN LOS DEFINE
define('NOMBRES2', ['Isaac', 'Abraham', 'Jose', 'Juan', 'Jesus']);
echo NOMBRES2[1] . "\n";
//!FIN EJEMPLO D
