<?php
// PROBANDO VARIABLES

// PASA INUMERABLES VECES EN NUESTRO CODIGO LA NECESIDAD DE VERIFICAR O PROBAR LA EXISTENCIA DE VARIABLE O DE SU VALOR

// PARA ESO PHP CONTIENE UN CONJUNTO DE CONSTRUCCIONES INTERNAS QUE NOS PERMITEN HACER VERIFICACIONES

//& ISSET
// ESTA CONSTRUCCION PERMITE VERIFICAR SI UNA VARIABLE ESTA O NO DEFINIDA, ELLA RETORNA VERDADERO SI LA VARIABLE EXISTE Y FALSO SI NO EXISTE.

$a = 1;
if (isset($a)) {
  echo "La variable existe \n";
} else {
  echo "La variable no existe \n";
}

// SI TENEMOS UNA VARIABLE DEFINIDA, PERO SU VALOR ES NULL, ES CONSIDERADA COMO UNA VARIABLE INEXISTENTE.
$b = null;
echo isset($b) ? "Existe" : "No existe";

//& EMPTY

// VERIFICA SI LA VARIABLE TIENE UN VALOR VACIO (NULL,0, FALSE O STRING VACIO) Y RETORNA VERDADERO O FALSO.

$c = "Isaac";
empty($c); //false

$c = false;
empty($c); //true

$nombre_vacios = [];
empty($nombre_vacios); //true

$otro = null;
empty($otro); //true
