<?php

//& IS_NULL
// VERIFICA SI ES NULL O NO

$b = "Isaac";
is_null($b); //false

$c = null;
is_null($c); //true

// CON PHP8 HUVO UN MUDANZA EN LA FORMA DE COMO IS NULL FUNCIONA.
// ANTERIORMENTE, AL PROBAR CON IS NULL UNA VARIABLE INEXISTENTE ERA PRESENTADO RESULTADO VERDADERO CON AVISO VACIO.
// CON PHP8 PASA A EXISTIR UN ERROR DE TIPO

is_null($d);
