<?php
//& UNSET
// PERMITE DESTRUIR UNA VARIABLE
// EXISTEN DOS FORMAS DE HACERLO, CON LIGERAS DIFERENCIAS DE PERFORMANCE Y ACTUACION EN EL SISTEMA.

$a = "Isaac";
unset($a);

$b = "Abraham";
$b = null;

// EN EL PRIMER CASO, LA VARIABLE ES LIBERADA Y EN EL PROXIMO CICLO DE LIMPIEZA(GARBAGE COLLECTOR) ELLA ES REMOVIDA DE LA MEMORIA.

// EN EL SEGUNDO CASO LA VARIABLE VA A CONTINUAR EN LA MEMORIA, PERO SIN VALOR ATRIBUIDO APESAR DE LIBERARLO DE LA MEMORIA, UNA VARIABLE SIN LA EXISTENCIA DE VALOR.

// ES RECOMENDABLE DE UTILIZAR UNSET PARA LIBERAR LA MEMORIA.
