<?php
// ----->  ADEMAS DE INCLUDE EXISTE OTRAS TRES FORMAS DE IMPORTACION DE SCRIPT
//* require
//* include_once
//* require_once

// EL REQUIRE ES MUY SIMILIAR AL INCLUDE
// LAS MISMAS REGLAS DE DEFINICION DEL CAMINO ES APLICADO
// LA DIFERENCIA ENTRE REQUIRE Y INCLUDE ES QUE EN EL CASO DE INCLUDE FALLAR EL CODIGO AVANZA CON UN AVISO
// EN EL CASO DEL REQUIRE FALLAR LA APLICACION TERMINA CON UN ERROR

// include 'test.php';
// echo 'momento 1';

// require 'test.php';
// echo 'momento 2';

// ----->   COMO ESCOGER CUAL USAR
// ES ACONSEJABLE EL USO DE REQUIRE, UNA VEZ QUE, SUCEDE UN ERROR DE IMPORTACION DEL SCRIPT, LA APLICACION NO IRAN AVANZAR CON ERRORES
